### ISSUE TITLE
Handle multiply-mapped anitya updates

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#226]
See this message:

https://apps.fedoraproject.org/datagrepper/id?id=2015-b2e3fab5-12a6-47b0-9ffc-c21d5789a2d0&is_raw=true&size=extra-large

It is a message from anitya where the upstream is mapped to *two* different packages in Fedora.  Our ``subtitle`` text should convey that somehow.

**Comment by Ghost-script** [comment]
@ralphbean , something like this will be okay? 
`A new version of "SQLAlchemy" has been detected: "1.0.0b1" in advance of "0.9.9" , mapped to packages "python-sqlalchemy" and "python-sqlalchemy0.5"`

**Comment by ralphbean** [comment]
Yeah, I like the first of the two options.  :)

**Comment by Ghost-script** [comment]
@ralphbean , okay. what about mapped to single package?
currently if a package is mentioned then instead of project name package name is used. https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/anitya.py#L127-L133

so for single package should i change to

`A new version of "SQLAlchemy" has been detected: "1.0.0b1" in advance of "0.9.9" , mapped to package "python-sqlalchemy"` 

or leave it as it is?

**Comment by ralphbean** [comment]
@Ghost-script I think either approach is fine.  If it feels like implementing one way over another is easier.. go for that.

**Comment by Ghost-script** [comment]
This issue has been fixed in #228, so closing it.
